# for i in range(5, 100, 5):
#     print(i)

yearly_salaries = [100000, 120000, 130000, 140000, 150000]

for salary in yearly_salaries:
    print(salary)

for index in range(len(yearly_salaries)):
    print(index, yearly_salaries[index])

# index is generated by enumerate, not REAL index
for index, value in enumerate(yearly_salaries):
    print(index, value)

gross_prices = []
net_prices = [10000, 12000, 13000, 14000, 15000]
hungarian_vat_percent = 27

for net_price in net_prices:
    gross_prices.append(net_price * (1 + hungarian_vat_percent / 100))
